## Overview
Features in the Iris dataset:
– sepal length (cm)
– sepal width (cm)
– petal length (cm)
– petal width (cm)
• Target classes to predict:
– Setosa
– Versicolour
– Virginica

In [ ]:
import sklearn
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [ ]:
from sklearn import datasets
abc=datasets.load_iris()
x=abc.data  # Samples in iris i.e.150 images
y=abc.target

In [ ]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
x[51:60]

array([[6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4]])

Here 150 images are sliced in 150
150 are then split into train and test
135 for train
15 for test
test_size=0.10  10 % test 90 %


In [ ]:
abc.target[51:60]

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.300, random_state=3)

In [ ]:
# create the linear model classifier

from sklearn.svm import SVC
# fit the model
clf=SVC(kernel='rbf')
clf.fit(x_train,y_train)

SVC()

In [ ]:
y_pred = clf.predict(x_test)

In [ ]:
print(x_test)

[[4.6 3.2 1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [5.  3.  1.6 0.2]
 [5.7 4.4 1.5 0.4]
 [7.7 2.6 6.9 2.3]
 [5.5 2.5 4.  1.3]
 [4.6 3.4 1.4 0.3]
 [6.3 2.9 5.6 1.8]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.1 1.3]
 [4.4 3.  1.3 0.2]
 [5.8 2.6 4.  1.2]
 [5.5 2.3 4.  1.3]
 [6.7 3.1 5.6 2.4]
 [5.  3.5 1.3 0.3]
 [6.3 2.5 4.9 1.5]
 [7.7 3.  6.1 2.3]
 [5.7 2.5 5.  2. ]
 [4.4 3.2 1.3 0.2]
 [6.2 2.8 4.8 1.8]
 [6.8 3.  5.5 2.1]
 [6.9 3.1 5.1 2.3]
 [6.8 2.8 4.8 1.4]
 [5.4 3.9 1.7 0.4]
 [7.2 3.6 6.1 2.5]
 [6.1 2.6 5.6 1.4]
 [5.8 2.7 4.1 1. ]
 [4.9 2.4 3.3 1. ]
 [6.7 3.1 4.7 1.5]
 [5.8 4.  1.2 0.2]
 [4.8 3.4 1.9 0.2]
 [6.9 3.1 5.4 2.1]
 [6.6 2.9 4.6 1.3]
 [4.4 2.9 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [6.7 3.  5.  1.7]
 [4.5 2.3 1.3 0.3]
 [6.4 2.7 5.3 1.9]
 [6.2 2.2 4.5 1.5]
 [6.4 2.8 5.6 2.1]
 [5.8 2.7 3.9 1.2]
 [4.6 3.6 1.  0.2]
 [5.1 3.5 1.4 0.3]
 [6.1 3.  4.9 1.8]]


In [ ]:
print(y_pred)

[0 0 0 0 0 2 1 0 2 1 1 0 1 1 2 0 1 2 2 0 2 2 2 1 0 2 2 1 1 1 0 0 2 1 0 0 2
 0 2 1 2 1 0 0 2]


In [ ]:
print(x_train.shape)
print(x_test.shape)
print(x_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105, 4)
(45,)


In [ ]:
y_test[0:5]

array([0, 0, 0, 0, 0])

In [ ]:
y_pred[0:5]

array([0, 0, 0, 0, 0])

In [ ]:
y_pred[20]

if (y_pred[20]==0):
    print(abc.target_names[0])
elif(y_pred[20]==1):
    print(abc.target_names[1])
else:
    print(abc.target_names[2])


virginica


In [ ]:
y_test[20]

2

In [ ]:
y_pred[20]

2

In [ ]:
# Training Accuracy
from sklearn import metrics
y_train_pred = clf.predict(x_train)
print(metrics.accuracy_score(y_train, y_train_pred))

0.9523809523809523


In [ ]:
#Testing Accuracy
y_pred = clf.predict(x_test)
print (metrics.accuracy_score(y_test, y_pred))

0.9333333333333333


In [ ]:
predicted = clf.predict(x_test[0:10])
expected = y_test[0:10]

In [ ]:
print(predicted)

[1 1 0 1 2 2 0 0 2 2]


In [ ]:
print(expected)

[1 1 0 1 2 2 0 0 2 2]


In [ ]:
# Training Accuracy
from sklearn import metrics
y_train_pred = clf.predict(x_train)
print(metrics.accuracy_score(y_train, y_train_pred))

0.9523809523809523


In [ ]:
#Testing Accuracy
y_pred = clf.predict(x_test)
print (metrics.accuracy_score(y_test, y_pred))

0.9333333333333333
