In [ ]:
import sklearn
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [ ]:
from sklearn import datasets
clf=datasets.load_breast_cancer()
x=clf.data  # Samples in iris i.e.150 images
y=clf.target

In [ ]:
print(clf.target_names)

['malignant' 'benign']


In [ ]:
clf.data[11:20]

array([[1.578e+01, 1.789e+01, 1.036e+02, 7.810e+02, 9.710e-02, 1.292e-01,
        9.954e-02, 6.606e-02, 1.842e-01, 6.082e-02, 5.058e-01, 9.849e-01,
        3.564e+00, 5.416e+01, 5.771e-03, 4.061e-02, 2.791e-02, 1.282e-02,
        2.008e-02, 4.144e-03, 2.042e+01, 2.728e+01, 1.365e+02, 1.299e+03,
        1.396e-01, 5.609e-01, 3.965e-01, 1.810e-01, 3.792e-01, 1.048e-01],
       [1.917e+01, 2.480e+01, 1.324e+02, 1.123e+03, 9.740e-02, 2.458e-01,
        2.065e-01, 1.118e-01, 2.397e-01, 7.800e-02, 9.555e-01, 3.568e+00,
        1.107e+01, 1.162e+02, 3.139e-03, 8.297e-02, 8.890e-02, 4.090e-02,
        4.484e-02, 1.284e-02, 2.096e+01, 2.994e+01, 1.517e+02, 1.332e+03,
        1.037e-01, 3.903e-01, 3.639e-01, 1.767e-01, 3.176e-01, 1.023e-01],
       [1.585e+01, 2.395e+01, 1.037e+02, 7.827e+02, 8.401e-02, 1.002e-01,
        9.938e-02, 5.364e-02, 1.847e-01, 5.338e-02, 4.033e-01, 1.078e+00,
        2.903e+00, 3.658e+01, 9.769e-03, 3.126e-02, 5.051e-02, 1.992e-02,
        2.981e-02, 3.002e-03, 1.684e

Here 150 images are sliced in 150
150 are then split into train and test
135 for train
15 for test
test_size=0.10  10 % test 90 %


In [ ]:
clf.target[11:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.300, random_state=33)

In [ ]:
# create the linear model classifier

from sklearn.svm import SVC
# fit the model
abc=SVC(kernel='rbf')
abc.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = abc.predict(x_test)

In [ ]:
print(x_test)

[[1.861e+01 2.025e+01 1.221e+02 ... 1.490e-01 2.341e-01 7.421e-02]
 [1.143e+01 1.731e+01 7.366e+01 ... 6.402e-02 2.584e-01 8.096e-02]
 [1.116e+01 2.141e+01 7.095e+01 ... 4.306e-02 2.976e-01 7.123e-02]
 ...
 [1.320e+01 1.582e+01 8.407e+01 ... 2.500e-02 2.651e-01 8.385e-02]
 [1.496e+01 1.910e+01 9.703e+01 ... 1.489e-01 2.962e-01 8.472e-02]
 [2.137e+01 1.510e+01 1.413e+02 ... 1.966e-01 2.730e-01 8.666e-02]]


In [ ]:
print(y_pred)

[0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 1 1 0
 0 1 0 0 0 1 0 1 1 1 1 0 1 0 0 1 1 0 0 1 1 0 1 0 1 1 0 1 1 1 1 0 1 0 1 0 1
 0 1 0 1 1 0 1 1 0 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 1 1 0
 1 1 0 1 1 0 1 1 0 0 1 1 1 0 1 1 1 1 0 0 1 1 0]


In [ ]:
print(x_train.shape)
print(x_test.shape)
print(x_train.shape)
print(x_test.shape)

(398, 30)
(171, 30)
(398, 30)
(171, 30)


In [ ]:
y_pred[20]

if (y_pred[20]==0):
    print(clf.target_names[0])
else:
    print(clf.target_names[1])



benign


In [ ]:
# Training Accuracy
from sklearn import metrics
y_train_pred = abc.predict(x_train)
print(metrics.accuracy_score(y_train, y_train_pred))

0.9246231155778895


In [ ]:
#Testing Accuracy
y_pred = abc.predict(x_test)
print (metrics.accuracy_score(y_test, y_pred))

0.8888888888888888


In [ ]:
predicted = abc.predict(x_test[0:10])
expected = y_test[0:10]

In [ ]:
print(predicted)

[0 1 1 1 1 0 1 1 1 1]


In [ ]:
print(expected)

[0 1 1 1 1 1 1 1 1 1]


In [ ]:
# Training Accuracy
from sklearn import metrics
y_train_pred = abc.predict(x_train)
print(metrics.accuracy_score(y_train, y_train_pred))

0.9246231155778895


In [ ]:
#Testing Accuracy
y_pred = abc.predict(x_test)
print (metrics.accuracy_score(y_test, y_pred))

0.8888888888888888


In [ ]:
# Precision
print (metrics.precision_score(y_test, y_pred))


0.864406779661017


In [ ]:
# Recall
print (metrics.recall_score(y_test, y_pred))

0.9714285714285714
